project_id = "kkgpinwpdjlsscooqvam"

[functions.islamic-ai]
verify_jwt = false

[functions.subscribe-push]
verify_jwt = false

[functions.send-prayer-notification]
verify_jwt = false

[functions.check-prayer-times]
verify_jwt = false